apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP # שירות פנימי בתוך הקלאסטר
  selector:
    app: shay-backend # חייב להתאים ל-label ב-Deployment
  ports:
    - protocol: TCP
      port: 80         # הפורט שדרכו רכיבים אחרים יפנו לבקנד
      targetPort: 8080  # הפורט שעליו הבקנד מאזין באמת