apiVersion: v1
kind: Secret
metadata:
  name: shay-project-secrets
type: Opaque
data:
  db-password: MTIzNDU=
  openai-api-key: c2stcHJvai15OFpDTGtFMFZudEFqOXJSdFp5UzR1Zl9aLUo2SnVjREZjMnUxQTQ1UXFVOVFjUG5FSlI4cWZRTF84M3VGMWtMSXgzN181cUtIMVQzQmxia0ZKNmJjR05WbV9CSm9VQW5MdTNaM3NvUnNrVURIalNiVG5QOGcwZzNlZlNHR1RhbG1mb19Ka3dRMjlITkRscXhvZXdSVUxCcDUwY0E=